### ISSUE TITLE
Error: Could not find a production build in the '.next' directory

### ISSUE THREAD

**Issue by duqingnian** [safak/next-social#2]
when i run "yarn start", i get this error, how to fix this? thanks a lot!
`D:\react\next-social>yarn start
yarn run v1.22.22
$ next start
  ▲ Next.js 15.0.0-rc.0
  - Local:        http://localhost:3000

 ✓ Starting...
Error: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at setupFsCheck (D:\react\next-social\node_modules\next\dist\server\lib\router-utils\filesystem.js:151:19)
    at async initialize (D:\react\next-social\node_modules\next\dist\server\lib\router-server.js:62:23)
    at async Server.<anonymous> (D:\react\next-social\node_modules\next\dist\server\lib\start-server.js:250:36)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

D:\react\next-social>`

**Comment by exgleowl** [comment]
Run `npm run  build` to create a production build before booting up the production server.
If your intention was to run the development server run `npm run dev` instead.

**Comment by duqingnian** [comment]
run "npm run build" command, get this message:
`D:\react\react-twitter-ui-clone>npm run  build

> twitter-clone@0.1.0 build
> react-scripts build

Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (D:\react\react-twitter-ui-clone\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\react\react-twitter-ui-clone\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (D:\react\react-twitter-ui-clone\node_modules\webpack\lib\NormalModule.js:471:10)
    at D:\react\react-twitter-ui-clone\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\react\react-twitter-ui-clone\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\react\react-twitter-ui-clone\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\react\react-twitter-ui-clone\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (D:\react\react-twitter-ui-clone\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
D:\react\react-twitter-ui-clone\node_modules\react-scripts\scripts\build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (D:\react\react-twitter-ui-clone\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\react\react-twitter-ui-clone\node_modules\webpack\lib\NormalModule.js:417:16)
    at D:\react\react-twitter-ui-clone\node_modules\webpack\lib\NormalModule.js:452:10
    at D:\react\react-twitter-ui-clone\node_modules\webpack\lib\NormalModule.js:323:13
    at D:\react\react-twitter-ui-clone\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\react\react-twitter-ui-clone\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\react\react-twitter-ui-clone\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\react\react-twitter-ui-clone\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v22.5.1

D:\react\react-twitter-ui-clone>
![npm_run_build_err_msg](https://github.com/user-attachments/assets/e2346734-255e-43cf-ab56-723a4b8f40ef)
`

**Comment by exgleowl** [comment]
Try in Unix:
`export NODE_OPTIONS=--openssl-legacy-provider`
In  Windows:
`set NODE_OPTIONS=--openssl-legacy-provider`

**Comment by duqingnian** [comment]
problem solved， Tanks a lot!
